### PR TITLE
docs: add python 3.9 availability to README.md

### PR DESCRIPTION
**Pull request by DahlitzFlorian**
As far as I can see and understand Python 3.9 is available through this repository as well. The availability should be documented for users in the `README.md`.

### CODE REVIEW

**Comment by asottile** [comment]
It's not usable yet afaik so it hasn't been documented (the code for py39 existed way before python3.9a1 was even out!)

**Comment by DahlitzFlorian** [comment]
Oh, i was too fast I guess!

**Comment by asottile** [comment]
yeah, you'll also want to add it to `azure-pipelines.yml` -- I wonder why it didn't trigger a build though :thinking:

**Comment by asottile** [comment]
oh, nevermind, I'm super confused on what repo this is lol

**Pull request merged**
